version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_NAME: postgres
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 4318
    depends_on:
      - db
      - jaeger
      - prometheus

  db:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "4318:4318"
      - "14268:14268"
      - "16686:16686"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3030"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD="amdin"
    volumes:
      - grafana-data:/var/lib/grafana


volumes:
  postgres-data:
  grafana-data: 
